/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sniperking_live555suihw_Live555Func */

#ifndef _Included_com_sniperking_live555suihw_Live555Func
#define _Included_com_sniperking_live555suihw_Live555Func
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sniperking_live555suihw_Live555Func
 * Method:    getUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sniperking_live555suihw_Live555Func_getUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_sniperking_live555suihw_Live555Func
 * Method:    start
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sniperking_live555suihw_Live555Func_start
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
